FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
#RUN pip install -r requirements.txt
RUN pip install --upgrade pip && \
    pip install --timeout=100 --retries=100 -r requirements.txt
    
COPY . .

CMD ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]
